### ISSUE TITLE
chown: /var/lib/mysql: Operation not permitted

### ISSUE THREAD

**Issue by fortis** [Wodby/drupal-compose#1]
Got an error with mounting ./mariadb:
YML:
>   volumes:
>     - ./mariadb:/var/lib/mysql

Console:
> Creating drupalcompose_db_1
Creating drupalcompose_app_1
Creating drupalcompose_web_1
Attaching to drupalcompose_db_1, drupalcompose_app_1, drupalcompose_web_1
db_1   | chown: /var/lib/mysql: Operation not permitted
app_1  | [14-Jul-2016 09:59:04] NOTICE: fpm is running, pid 1
db_1   | Cannot change ownership of the database directories to the 'mysql'
app_1  | [14-Jul-2016 09:59:04] NOTICE: ready to handle connections
db_1   | user.  Check that you have the necessary permissions and try again.
drupalcompose_db_1 exited with code 1

**Comment by fortis** [comment]
but it works without mariadb volume

**Comment by fortis** [comment]
Seems that chown is not necessary.
There is 'ls' command output just before chown:

> Step 6 : RUN ls -la var/lib
 ---> Running in 3c6879007fc4
total 24
drwxr-xr-x    6 root     root          4096 Jul 14 10:07 .
drwxr-xr-x   15 root     root          4096 Jul 14 10:07 ..
drwxr-xr-x    2 root     root          4096 Jun 23 19:37 apk
drwxr-xr-x    2 root     root          4096 Jun 23 19:37 misc
drwxr-sr-x    2 mysql    mysql         4096 Jul 14 10:07 mysql
drwxr-xr-x    2 root     root          4096 Jun 23 19:37 udhcpd

**Comment by fortis** [comment]
found solution, upgrading to recent docker version will fix it
MAC: https://docs.docker.com/docker-for-mac/
@csandanov probably it makes sense to add Troubleshooting section on homepage

**Comment by fortis** [comment]
nope, upgrade doesn't solve the problem. 
https://github.com/adlogix/docker-machine-nfs caused an error, but with recent docker version for mac os we don't need docker-machine-nfs anymore  (vbox has gone)

**Comment by PavelPrischepa** [comment]
@fortis, yes, you are right chown is not necessary. Fixed. Thank you!

**Comment by smurrayatwork** [comment]
With the latest code, this appears to still be happening and the chown still exists.
